hts-precompile/HederaTokenService.sol, hts-precompile/IHederaTokenService.sol
=> Call update

hts-precompile/IHederaTokenService.sol
HIP 514 adds coverage for the missing HTS HAPI function in precompile.
Add missing functions to `IHederaTokenService.sol`
Fixes #10 
Fixes  #13 
Fixes #14 
Fixes  #15 
Fixes #16 
Fixes #17 
Fixes #18 
Fixes #19 
Fixes #20 
Fixes #21 
Fixes #22 
Fixes #24 
**Checklist**
=> Add token management functions to IHederaTokenService

hts-precompile/IHederaTokenService.sol
Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>
Add function to to check validity of token to the interface.  Specifically added
function isToken(address token) 
external returns 
(int64 responseCode, bool isToken);
and 
function getTokenType(address token)
external returns 
(int64 responseCode, int32 tokenType);
Fixes #38 
**Checklist**
=> add token validity functions

hts-precompile/HederaTokenService.sol
Signed-off-by: georgi-l95 <glazarov95@gmail.com>
Add missing HIP 514 functions
Fixes #23 
**Checklist**
=> Update HederaTokenService.sol with missing HIP 514 functions

hts-precompile/FeeHelper.sol
Signed-off-by: <georgi-l95 glazarov95@gmail.com>
Updated FeeHelper contract with improvement methods
Fixes #51 
**Checklist**
=> Update FeeHelper contract

contracts/hts-precompile/HederaTokenService.sol, contracts/hts-precompile/IHederaTokenService.sol, contracts/hts-precompile/TokenCreate.sol, contracts/hts-precompile/examples/token-create/TokenCreateContract.sol, test/safe-hts-precompile/SafeHTS.js
Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>
Update structs to add boolean for allowance. Update the function signature to also pass in changes to hbar balances in addition to the existing token transfers.
Fixes #69
=> Enhance support for atomic crypto transfers

README.md
Update README with 
- Contribution details
- Overview for different smart contracts
Fixes #86 
**Checklist**
=> Update README with contribution details

package.json
Bump 0.3.0-SNAPSHOT
Fixes #
**Checklist**
=> Bump 0.3.0-SNAPSHOT

README.md, package.json
Bump 0.2.0-rc1
Fixes #
**Checklist**
=> Bump 0.2.0-rc1

.github/workflows/release-production.yml
Add npm artifact github action
Fixes #
**Checklist**
=> Add npm artifact

.github/workflows/release-production.yml
Add npm artifact github action for use in releases
Cherry pick Npm artifact to release/0.1
Fixes #
**Checklist**
=> Npm artifact for v0.1

.github/workflows/release-production.yml
Add npm artifact github action for use in releases
Cherry pick npm artifact github action for v0.2
Fixes #
**Checklist**
=> Npm artifact for v0.2

.github/workflows/tests.yml, test/hts-precompile/token-managment/tokenManagmentContract.js
Add test for the following functions:
- [deleteToken](https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/hts-precompile/IHederaTokenService.sol#L624)
- [freezeToken](https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/hts-precompile/IHederaTokenService.sol#L698)
-  [removeTokenKyc](https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/hts-precompile/IHederaTokenService.sol#L722)
-  [pauseToken](https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/hts-precompile/IHederaTokenService.sol#L729)
-  [wipeToken](https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/hts-precompile/IHederaTokenService.sol#L741)
-  [wipeTokenAccountNFT](https://github.com/hashgraph/hedera-smart-contracts/ …
=> Add Token Management Contract test coverage

contracts/hts-precompile/examples/erc-20/ERC20Contract.sol, test/hts-precompile/erc-20/ERC20Contract.js
Signed-off-by: Ivo Yankov <ivo@devlabs.bg>
- Adds the methods `delegateApprove` and `delegateTransferFrom` to `ERC20Contract.sol`
- Adds tests for all contract methods
Fixes #105 
**Checklist**
=> ERC20 test coverage

test/hts-precompile/erc-721/ERC721Contract.js, test/hts-precompile/utils.js
Adds negative tests for:
- approve
- transferFrom
- safeTransferFrom
- safeTransferFromWithData
- tokenByIndex
- tokenOfOwnerByIndex
Fixes #106 
**Checklist**
=> ERC721 Test Coverage

.github/workflows/test-workflow.yml, package-lock.json, package.json
Signed-off-by: nikolay <n.atanasow94@gmail.com>
Fixes #157
**Checklist**
=> Bump the images

README.md
Signed-off-by: nikolay <n.atanasow94@gmail.com>
Fixes #170
**Checklist**
=> README has a broken link and inconsistent text

package.json
=> Bump 0.3.0-rc1

README.md
README updated with version of services to map to.
Fixes #189
=> Added line describing what version of services this maps to.

package.json
=> Set the version release.

package.json
Bump PR.  0.4.0-SNAPSHOT
Fixes #189
=> Bump snapshot version.

.github/workflows/tests.yml
Add ERC1155 in CI
Fixes #211 
**Checklist**
=> Add ERC1155 in CI

.github/workflows/test-workflow.yml, package-lock.json, package.json
This PR bumps acceptance test network image to `0.37.0` and mirror-node images to `0.79.0-beta.1` .
Also bump local-node package
Fixes #
**Checklist**
=> Bump Tests images

test/diamond-pattern/diamond.js, test/erc-1155/ERC1155.js, test/erc-20/ERC20.js, test/erc-721/ERC721.js, test/hip-583/HIP583.js, test/hts-precompile/assertions.js, test/hts-precompile/erc-20/ERC20Contract.js, test/hts-precompile/erc-721/ERC721Contract.js, test/hts-precompile/redirect-for-token.js, test/hts-precompile/token-create/tokenCreateContract.js, test/hts-precompile/token-managment/tokenManagmentContract.js, test/hts-precompile/token-query/tokenQueryContract.js, test/hts-precompile/token-transfer/tokenTransferContract.js, test/hts-precompile/utils.js, test/proxy-upgrade/proxyUpgradeContracts.js, test/safe-hts-precompile/SafeHTS.js
**Description**: Adding apache license headers to all tests in the smart contract project. 
Fixes # 216
**Checklist**
=> Adding missing license headers

test/constants.js, test/diamond-pattern/diamond.helper.js, test/diamond-pattern/diamond.js, test/erc-1155/ERC1155.js, test/erc-20/ERC20.js, test/erc-721/ERC721.js, test/hip-583/HIP583.js, test/hts-precompile/erc-20/ERC20Contract.js, test/hts-precompile/erc-721/ERC721Contract.js, test/hts-precompile/redirect-for-token.js, test/hts-precompile/token-create/tokenCreateContract.js, test/hts-precompile/token-managment/tokenManagmentContract.js, test/hts-precompile/token-query/tokenQueryContract.js, test/hts-precompile/token-transfer/tokenTransferContract.js, test/hts-precompile/utils.js, test/proxy-upgrade/proxyUpgradeContracts.js, test/safe-hts-precompile/SafeHTS.js
This PR refactors part of the tests and extract constants, paths and contracts in a new constants.js file.
Fixes #210 
**Checklist**
=> Refactor constants

test/constants.js, test/erc-20-extensions/ERC20Extensions.js
**Description**: Enhance test consistency by refactoring variables in the erc20 extension tests and moving constants to the existing constants file.
Fixes #221 
**Checklist**
=> Remove constants from erc20 extension tests

.github/workflows/test-workflow.yml, .github/workflows/tests.yml, hardhat.config.js, package-lock.json, package.json
This PR updates the test pipelines to improve reporting of test results. It also prevents the use of `.only` in test suites and fails tests if 0 tests have been run in a suite.
* Add reporters as dev dependencies
* Modify hardhat config
* Update workflows
Fixes #223
**Checklist**
=> Add test reporting to pipelines

contracts/hts-precompile/examples/token-create/TokenCreateContract.sol, test/hts-precompile/redirect-for-token.js
**Description**: Fix for redirect for token test
Fixes #227 
**Checklist**
=> Redirect for token test fix

test/hts-precompile/erc-20/ERC20Interface.js, test/hts-precompile/erc-20/IERC20.js
=> Add direct ERC call examples

system-contract-dapp-playground/package-lock.json, system-contract-dapp-playground/package.json, system-contract-dapp-playground/src/api/cookies/index.ts, system-contract-dapp-playground/src/api/wallet/index.ts, system-contract-dapp-playground/src/app/(protected)/overview/page.tsx, system-contract-dapp-playground/src/components/toast/CommonToast.tsx, system-contract-dapp-playground/src/middleware.ts, system-contract-dapp-playground/src/sections/landing/index.tsx, system-contract-dapp-playground/src/types/interfaces.d.ts, system-contract-dapp-playground/src/utils/constants.ts, system-contract-dapp-playground/tailwind.config.js
**Description**: This PR adds the connect wallet feature to the dapp
UI flow:
a. If the current wallet does not match the expected Hedera networks, a toast will pop up to prompt users to follow the appropriate guidelines for user and network configuration.
b. When the network is configured properly, request accounts by calling eth_requestAccounts
c. After connecting the account, the information will be stored in Cookies. At the same time, the user will be navigated to the first protected route "/overview".
Fixes: #277
=> feat: added connect wallet feature to Dapp

system-contract-dapp-playground/README.md, system-contract-dapp-playground/contracts-info/index.ts, system-contract-dapp-playground/package-lock.json, system-contract-dapp-playground/package.json, system-contract-dapp-playground/scripts/prerequisite-check.ts, system-contract-dapp-playground/src/sections/landing/index.tsx
**Description**: This PR added a quick script that does the `prerequisite check` for smart contract assets needed in the DApp Playground
Fixes #280 
**Checklist**
=> feat: added validation check for contract metadata (#280)

system-contract-dapp-playground/contracts-info/index.ts, system-contract-dapp-playground/src/api/wallet/index.ts, system-contract-dapp-playground/src/app/hedera/hts-hip-206/page.tsx, system-contract-dapp-playground/src/components/footer/index.tsx, system-contract-dapp-playground/src/components/navbar/index.tsx, system-contract-dapp-playground/src/components/wallet-popup/index.tsx, system-contract-dapp-playground/src/sections/hts-hip-206/index.tsx, system-contract-dapp-playground/src/sections/landing/index.tsx, system-contract-dapp-playground/src/styles/globals.css, system-contract-dapp-playground/src/types/interfaces.d.ts, system-contract-dapp-playground/src/utils/constants.ts, system-contract-dapp-playground/tailwind.config.js, system-contract-dapp-playground/tsconfig.json
**Description**: This PR adds a new UI component for HTS-206 route and reworked smart contract assets for better information and access within React app
Fixes #302 
**UI update**:
**Checklist**
=> feat: added new UI component for HTS-206 route & reworked smart contract assets (#302)

system-contract-dapp-playground/src/app/hedera/hrc-719/page.tsx, system-contract-dapp-playground/src/sections/hrc-719/index.tsx, system-contract-dapp-playground/src/sections/hts-hip-206/index.tsx, system-contract-dapp-playground/src/types/interfaces.d.ts, system-contract-dapp-playground/src/utils/constants.ts
**Description**: This PR adds new UI for hrc-719 route and added deployment support and contract details for HRCContract
Fixes #283
**UI update**
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/41c6e544-d024-4282-9a91-6b50be49e2d9
**Checklist**
=> feat: Added deployment support and deployed contract details for HRCcontract.sol (#283)

system-contract-dapp-playground/src/app/hedera/exchange-rate-hip-475/page.tsx, system-contract-dapp-playground/src/components/common/AlertDialog.tsx, system-contract-dapp-playground/src/components/common/HederaCommonTextField.tsx, system-contract-dapp-playground/src/components/contract-interaction/index.tsx, system-contract-dapp-playground/src/components/exchange-rate-hip-475/ExchangeRateDeployField.tsx, system-contract-dapp-playground/src/sections/exchange-rate-hip-475/index.tsx, system-contract-dapp-playground/src/types/interfaces.d.ts, system-contract-dapp-playground/src/utils/constants.ts, system-contract-dapp-playground/src/utils/helpers.ts
**Description**: This PR adds a new UI section component for exhcnage-rate-hip-475 route, deployment support and deployed contract details for exchangeRatePrecompile smart contract
Fixes #289 
**UI update**:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/e605e17a-5127-4761-b9ed-e6f52b637233
**Checklist**
=> feat: Added deployment support and deployed contract details for exchangeRatePrecompile.sol (#289)

system-contract-dapp-playground/src/app/hedera/prng-hip-351/page.tsx, system-contract-dapp-playground/src/components/contract-interaction/index.tsx, system-contract-dapp-playground/src/sections/prng-hip-351/index.tsx
**Description**: This PR adds a new section UI for hip351 route, new deployment support and deployed contract details for prngSystemContract
Fixes #290 
** UI update **
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/9d1147f4-c2c1-4504-bf92-b8be6e6aacf9
**Checklist**
=> feat: Added deployment support and deployed contract details for prngSystemContract.sol (#290)

system-contract-dapp-playground/src/app/hedera/erc-20/page.tsx, system-contract-dapp-playground/src/components/common/HederaCommonTextField.tsx, system-contract-dapp-playground/src/components/contract-interaction/index.tsx, system-contract-dapp-playground/src/components/erc/ERCDeployField.tsx, system-contract-dapp-playground/src/sections/erc-20/index.tsx
**Description**: This PRs add a new UI section for erc-20 route, deployment support and detailed contract for ERC20 Contract
Fixes #285 
** UI update **
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/77fd1e1b-b8c9-424b-968e-61100a83235b
**Checklist**
=> feat: Added deployment support and deployed contract details for erc20Contract.sol (#285)

system-contract-dapp-playground/src/app/hedera/erc-721/page.tsx, system-contract-dapp-playground/src/components/contract-interaction/index.tsx, system-contract-dapp-playground/src/components/footer/index.tsx, system-contract-dapp-playground/src/components/leftSideBar/index.tsx, system-contract-dapp-playground/src/components/navbar/index.tsx, system-contract-dapp-playground/src/sections/erc-20/index.tsx, system-contract-dapp-playground/src/sections/erc-721/index.tsx, system-contract-dapp-playground/src/sections/exchange-rate-hip-475/index.tsx, system-contract-dapp-playground/src/sections/hrc-719/index.tsx, system-contract-dapp-playground/src/sections/hts-hip-206/index.tsx, system-contract-dapp-playground/src/sections/landing/index.tsx, system-contract-dapp-playground/src/sections/overview/index.tsx, system-contract-dapp-playground/src/sections/prng-hip-351/index.tsx, system-contract-dapp-playground/src/utils/constants.ts
**Description**: This PR adds new UI section for erc-721 route, deployment support and contract details for ERC721Contract
Fixes #284 
** UI updates **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/bf416a28-f77d-4ea0-8ad3-723240f31836
**Checklist**
=> feat: Add deployment support and deployed contract details for ERC721Contract.sol (#284)

system-contract-dapp-playground/src/api/ethers/index.ts, system-contract-dapp-playground/src/components/contract-interaction/erc/deployment/ERCDeployField.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/common/MultiLineMethod.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/common/OneLineMethod.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/BalanceOf.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Mint.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenInformation.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenPermissions.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Transfer.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/utils/constant.ts, system-contract-dapp-playground/src/components/contract-interaction/exchange-rate-hip-475/deployment/ExchangeRateDeployField.tsx, system-contract-dapp-playground/src/components/contract-interaction/index.tsx, system-contract-dapp-playground/src/types/interfaces.d.ts, system-contract-dapp-playground/src/utils/constants.ts, system-contract-dapp-playground/src/utils/helpers.ts
**Description**: This PR adds an UI component for ERC20Mock interactions
**Related issue(s)**: #314, #321
Fixes #325 
**Notes for reviewer**: The data in the UI demo below is only temporary
**UI demo**:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/95d2ace8-668e-48f1-b34f-1b1fc5afa931
**Checklist**
=> feat: Added new UI component for ERC20Mock contract interactions (#325)

test/hts-precompile/token-create/tokenCreateContract.js
**Description**: this PR replaced tokenCreateCustomContract with tokenCreateContract in `Hapi vs Ethereum` test suite to keep the consistent use of the tokenCreateContract within tokenCreateContract.js test file
Fixes #
**Checklist**
=> update: replaced tokenCreateCustomContract with tokenCreateContract in `Hapi vs Ethereum` test suite

system-contract-dapp-playground/__tests__/hedera/erc20-interactions/index.test.ts, system-contract-dapp-playground/src/api/hedera/erc20-interactions/index.ts, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenInformation.tsx
**Description**: This PR adds new APIs and unit tests for token information querying feature and integrated it to the UI
**Related issue(s)**: #326
Fixes #335
** UI demo **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/7001f577-6e57-4d11-9da6-18f8bba3e0f0
**Checklist**
=> dapp-feat: added APIs, unit tests for tokenInformation and integrated new logic to TokenInformation UI component (#335)

system-contract-dapp-playground/__tests__/hedera/erc20-interactions/index.test.ts, system-contract-dapp-playground/src/api/hedera/erc20-interactions/index.ts, system-contract-dapp-playground/src/api/localStorage/index.ts, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/BalanceOf.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Mint.tsx
**Description**: This PR adds APIs and unit tests to support minting token and querying token balance features. It also integrated the new logic to the corresponded UI
**Related issue(s)**: #326 
Fixes #336 #337 
** UI demo **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/2d991f68-6e23-493f-99d5-78b26ce31e7f
**Checklist**
=> feat: added APIs & unit tests to support minting tokens and querying token balance (#336 #337)

system-contract-dapp-playground/__tests__/hedera/erc20-interactions/index.test.ts, system-contract-dapp-playground/src/api/hedera/erc20-interactions/index.ts, system-contract-dapp-playground/src/api/localStorage/index.ts, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenPermissions.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/utils/constant.ts
**Description**: 
This PR 
- added APIs and unit tests to support the flow for the token permissions features. It has 4 erc20 methods including approve(), increaseAllowance(), decreaseAllowance(), allowance(). 
- integrated the logic to the corresponded UI component
**Related issue(s)**:  #326 
Fixes #338 
** UI demo **
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/cc6fd29d-56cf-44ae-9b21-178e60e8d9d0
**Checklist**
=> feat: added APIs, unit tests for token permissions and integrated new logic to TokenPermissions UI component (#338)

system-contract-dapp-playground/__tests__/hedera/erc20-interactions/index.test.ts, system-contract-dapp-playground/src/api/hedera/erc20-interactions/index.ts, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Transfer.tsx
**Description**: This PR
- added APIs and unit tests to support the logic for erc20 Token Transfers (transfer() and transferFrom())
- integrated new logic to the corresponded UI
**Related issue(s)**: #326 
Fixes #339 
** UI demo **
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/a750d993-70ba-41ae-9ef7-c69a2fab21a4
**Checklist**
=> dapp-feat: added APIs, unit tests for token transfer and integrated new logic to Transfer UI component (#339)

system-contract-dapp-playground/__tests__/hedera/helper/index.test.ts, system-contract-dapp-playground/__tests__/hedera/hts-interactions/index.test.ts, system-contract-dapp-playground/src/api/hedera/tokenCreateCustom-interactions/index.ts, system-contract-dapp-playground/src/api/localStorage/index.ts, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenPermissions.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/shared/sharedComponents.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/shared/sharedMethods.tsx, system-contract-dapp-playground/src/components/contract-interaction/index.tsx, system-contract-dapp-playground/src/types/contract-interactions/HTS/index.d.ts, system-contract-dapp-playground/src/utils/common/constants.ts, system-contract-dapp-playground/src/utils/common/helpers.ts, system-contract-dapp-playground/src/utils/contract-interactions/HTS/constant.ts, system-contract-dapp-playground/src/utils/contract-interactions/HTS/helpers.ts
**Description**: This PR prepare a set of UI components and methods to integrate the tokenCreateCustom contract's methods which
- added helper functions and update utils methods' logic
- reworked error handling logic for APIs
- added HederaTokenCreateMethods parant component to main layout
- added sharedMethods and sharedComponents which will be used across TokenCreateCustom contract
Fixes partial #316
**Notes for reviewer**: No UI update yet, this is just the beginning setup
**Checklist**
=> feat: set up UI components and methods for integrating the tokenCreateCustom contract's methods into the DApp

system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/MetadataInputForm.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/hooks/usePaginatedTxResults.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/hooks/useToastSuccessful.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/hooks/useUpdateLocalStorage.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleRetrievingTransactionResultsFromLocalStorage.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/states/commonStates.ts, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/FungibleTokenCreate.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/MintHederaToken.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/NonFungibleTokenCreate.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/index.tsx
- refactored Fungible and Nonfungible Token Create components
- added the NonFungibleTokenCreate UI component which enables the use of both createNonFungibleTokenPublic() and createNonFungibleTokenWithFee() functions
Fixes partial #316 
** UI Demo **
a. Fungible Mint
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/223b006f-5e2c-4514-8f88-702076e93f12
b. Non-fungible Mint
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/b033644d-5a7f-4195-adcb-fd0c3b19077a
**Checklist**
=> feat: incorporated UI component for the MintHederaToken method

system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/MetadataInputForm.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/ParamInputForm.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TokenAddressesInputForm.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/hooks/useToastSuccessful.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/hooks/useUpdateLocalStorage.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleSanitizeFormInputs.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/AssociateHederaToken.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/GrantTokenKYC.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/index.tsx, system-contract-dapp-playground/src/utils/contract-interactions/HTS/token-create-custom/constant.ts
This PR added the NonFungibleTokenCreate UI component which enables the use of both TokenAssociation() and GrantTokenKYC() functions
Fixes #316
a. Token Association
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/d9cec6f4-01f7-4a85-acb2-f1a445ca79d8
b. Grant Token KYC
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/68d4c33d-f7f4-4d5e-a2ca-6af593004085
** updated UI **
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/5337b9a6-374a-4ad0-b3b3-4ce8a4c149e8
**Checklist**
=> feat: incorporated UI component for the TokenAssociation & GrantTokenKYC method 

system-contract-dapp-playground/__tests__/hedera/hts-interactions/token-management-contract/index.test.ts, system-contract-dapp-playground/src/api/hedera/tokenManagement-interactions/index.ts, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleSanitizeFormInputs.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/FungibleTokenCreate.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenPermission/index.tsx
**Description**: ManageTokenPermission feature complete
Fixes partial #316 
** UI Demo **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/1a60cb21-b552-4e9e-aff9-02d820b3f563
**Checklist**
=> 317 (token permission) add contract interacting features to token management contract contract

system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleSanitizeFormInputs.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenPermission/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenStatus/index.tsx, system-contract-dapp-playground/src/utils/contract-interactions/HTS/token-management/constant.ts
**Description**: ManageTokenStatus feature complete
Fixes partial #317 
** UI Demo **
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/10b91d01-49a5-4f0c-a2fd-ce87e9ac2b28
**Checklist**
=> dapp-feat: finished integrating ManageTokenStatus APIs to interact with TokenManage contract

system-contract-dapp-playground/__tests__/hedera/hts-interactions/token-management-contract/index.test.ts, system-contract-dapp-playground/src/api/hedera/tokenManagement-interactions/index.ts, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TokenAddressesInputForm copy.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleSanitizeFormInputs.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenRelation/index.tsx, system-contract-dapp-playground/src/utils/contract-interactions/HTS/token-create-custom/constant.ts
**Description**: ManageTokenRelation Feature complete
Fixes partial #317
** UI Demo **: 
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/b544f732-15a3-4bfa-9076-e20ba5089c92
**Checklist**
=> dapp-feat: finished integrating ManageTokenRelation APIs to interact with TokenManage contract

system-contract-dapp-playground/__tests__/hedera/hts-interactions/token-management-contract/index.test.ts, system-contract-dapp-playground/src/api/hedera/tokenManagement-interactions/index.ts, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleSanitizeFormInputs.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenDeduction/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenDelete/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenRelation/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenSupplyReduction/index.tsx, system-contract-dapp-playground/src/utils/common/constants.ts
**Description**: ManageTokenDeduction feature complete
Fixes #317 
** UI Demo **
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/a41db58b-7653-44b7-afe2-d325a21a9ece
** Updated UI Demo **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/50fa782f-0380-46cd-9432-739d3104c595
**Checklist**
=> dapp-feat: finished integrating ManageTokenDeduction APIs to interact with TokenManage contract

system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TokenPermissionInfoModal.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TransactionResultTable.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleSanitizeFormInputs.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/querySpecificToken/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenPermission/index.tsx
This PR finished integrating QueryTokenPermission to the dapp
Fixes partial #318
** UI Demo **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/76571c10-43d6-4966-aa7e-debb91e60100
**Checklist**
=> dapp-feat: QueryTokenPermission feature complete (#318)

system-contract-dapp-playground/__tests__/hedera/hts-interactions/token-query-contract/index.test.ts, system-contract-dapp-playground/src/api/hedera/tokenQuery-interactions/index.ts, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TransactionResultTable.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleSanitizeFormInputs.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenRelation/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenStatus/index.tsx, system-contract-dapp-playground/src/utils/common/constants.ts, system-contract-dapp-playground/src/utils/contract-interactions/HTS/token-query/constant.ts
This PR finished integrating QueryTokenPermission to the dapp
Fixes #318
** UI Demo **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/b73250ab-6489-4810-a4d8-aea428fb2d54
** Updated UI **:
**Checklist**
=> dapp-feat: QueryTokenRelation feature complete (#318)

system-contract-dapp-playground/__tests__/hedera/hts-interactions/token-create-custom/index.test.ts, system-contract-dapp-playground/__tests__/hedera/hts-interactions/token-transfer-contract/index.test.ts, system-contract-dapp-playground/src/api/hedera/tokenCreateCustom-interactions/index.ts, system-contract-dapp-playground/src/api/hedera/tokenManagement-interactions/index.ts, system-contract-dapp-playground/src/api/hedera/tokenQuery-interactions/index.ts, system-contract-dapp-playground/src/api/hedera/tokenTransfer-interactions/index.ts, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/AssociateHederaToken.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/GrantTokenKYC.tsx, system-contract-dapp-playground/src/types/contract-interactions/HTS/index.d.ts, system-contract-dapp-playground/src/utils/contract-interactions/HTS/helpers.ts
This PR adds a suite of new interfaces, APIs for the TokenTransferContract, and unit tests for the APIs
Fixes partial #319 
**Checklist**
=> dapp-feat: finished integrating TokenTransfer API Methods (#319)

system-contract-dapp-playground/__tests__/hedera/hts-interactions/token-transfer-contract/index.test.ts, system-contract-dapp-playground/src/api/hedera/tokenTransfer-interactions/index.ts, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/CryptoTransferInputFields.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TokenPermissionInfoModal.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TransactionResultTable.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleAPIErrors.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleSanitizeFormInputs.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-transfer-contract/method/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-transfer-contract/method/transferCrypto/TokenTransferForm.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/token-transfer-contract/method/transferSingleToken/index.tsx, system-contract-dapp-playground/src/types/contract-interactions/HTS/index.d.ts, system-contract-dapp-playground/src/utils/common/constants.ts, system-contract-dapp-playground/src/utils/contract-interactions/HTS/token-transfer/paramFieldConstant.ts
- merged TransferSingleToken and TransferSingleTokenFrom into 1 API group
- updated util components for TransferSingleToken
- finished integrating TransferSignleToken and TransferSignleTokenFrom
Fixes partial #319
** UI Demo **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/3d6e4cdd-a324-40cf-9623-75230141107e
**Checklist**
=> dapp-feat: TransferToken feature complete (#319)

.github/workflows/dapp-playground-workflow.yml, .github/workflows/system-contract-dapp.yml, system-contract-dapp-playground/package.json, system-contract-dapp-playground/src/api/hedera/tokenTransfer-interactions/index.ts
- CI task for ABI regression
- CI task for production-ready build
- CI task for unit test
- added a doc comment for in TransferTokens
**Related issue(s)**: #390 
Fixes #307
Fixes #388
Fixes #389 
**Checklist**
=> feat: added initial CI tasks for DApp Playground

system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/balance-of/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/token-permission/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/balance-of/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/owner-of/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/token-uri/index.tsx, system-contract-dapp-playground/src/components/contract-interaction/erc/shared/hooks/useUpdateMapStateUILocalStorage.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TokenGeneralInfoModal.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TokenPermissionInfoModal.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TokenSpecificInfoModal.tsx, system-contract-dapp-playground/src/components/contract-interaction/hts/shared/components/TransactionResultTable.tsx, system-contract-dapp-playground/src/components/contract-interaction/index.tsx, system-contract-dapp-playground/src/sections/activity/index.tsx, system-contract-dapp-playground/src/utils/common/constants.ts, system-contract-dapp-playground/src/utils/contract-interactions/erc/erc721/constant.ts
- BalanceOf feature complete  
- OwnerOf feature complete
- pull common attributes from constants
Fixes partial #322 
** UI Demo **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/2bf73b60-856d-4940-b755-4d02cf3cce38
**Checklist**
=> dapp-feat: ERC721 BalanceOf and OwnerOf feature complete

contracts/solidity/errors/Errors.sol, test/constants.js, test/solidity/errors/errors.js
Adding tests for the Errors in Solidity
https://github.com/hashgraph/hedera-smart-contracts/issues/443
Fixes #
N/A
=> Adding tests for the Errors in Solidity

.github/workflows/solidity-tests.yml
Adding new solidity tests GH test workflow.  Related issues: #430 
Fixes #
=> Adding solidity workflow.

TEST_SETUP.md
This PR adds a tutorial on installing foundry and forge to TEST_SETUP doc
**Related issue(s)**: #506 
Fixes #506 
**Checklist**
=> docs: added tutorial on installing foundry and forge to TEST_SETUP doc (#506)

package.json
Bump 0.6.0-rc1
**Related issue(s)**: #558 
Fixes #
**Checklist**
=> Bump 0.6.0-rc1

package.json
Bump 0.7.0-SNAPSHOT
**Related issue(s)**: #558
Fixes #
**Checklist**
=> Bump 0.7.0-SNAPSHOT

contracts/OZ/finance/VestingWallet.sol, test/OZ/finanace/VestingWallet.js
This PR adds VestingWallet contract from OZ contracts
Fixes #554 
**Checklist**
=> feat: added VestingWallet solidity example contract (#554)

contracts/oz/multicall/MulticallTest.sol, test/constants.js, test/solidity/oz/multicall/multicall.js
Adding tests for multicall example
Add OZ Multicall example #544
=> Adding tests for [OZ] Multicall example

contracts/solidity/block/BlockInfo.sol, test/constants.js, test/solidity/block/BlockInfo.js
Tests covering the Block properties.
**Related issue(s)**: 
Fixes #430
=> Block information tests.

contracts/solidity/oz/ERC-2771/ERC2771Context.sol, test/solidity/oz/erc-2771/context.js
Adding tests for ERC-2771 Context
Add OZ ERC2771Context example #556
=> Adding tests for [OZ] ERC-2771 Context

contracts/OZ/create2/ContractCreatorOZCreate2.sol, test/OZ/create2/ContractCreatorOZCreate2.js
- added ContractCreatorOZCreate2 contract to showcase the capabilities of OZ/Create2 library
- added unit tests for ContractCreatorOZCreate2 contract
Fixes #568 
**Checklist**
=> feat: added ContractCreatorOZCreate2 solidity example contract (#568)

contracts/solidity/oz/ReentrancyGuard/ReentrancyGuardTestReceiver.sol, contracts/solidity/oz/ReentrancyGuard/ReentrancyGuardTestSender.sol, test/constants.js, test/solidity/reentrancy/reentrancy.js
This PR adds test for the OZ ReentrancyGuard contract
Fixes #565
=> Adds test for reentrancy guard

.github/workflows/flow-pr-title-check.yml
This PR adds workflow, which is responsible for checking the title of the PR and if it's compliant with the Conventional Commits standard
Fixes #
**Checklist**
=> feat: add PR title check workflow

contracts/README.md
**Description**: This PR adds a new README under ocntracts/ folder to explain its layout
Fixes #621 
**Checklist**
=> feat(docs): added new README file under contracts/ folder (#621)

package-lock.json, package.json
Bump 0.7.0-rc1
**Related issue(s)**: #630 
Fixes #
**Checklist**
=> docs: Bump 0.7.0-rc1

package-lock.json, package.json
Bump 0.8.0-SNAPSHOT
Fixes #630 
**Checklist**
=> docs: Bump 0.8.0-SNAPSHOT

package-lock.json, package.json
This PR updates local node to latest version
Fixes #
**Checklist**
=> chore: update local node

package-lock.json, package.json
Bumps [@openzeppelin/contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) from 5.0.0 to 5.0.2.
- [Release notes](https://github.com/OpenZeppelin/openzeppelin-contracts/releases)
- [Changelog](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/CHANGELOG.md)
- [Commits](OpenZeppelin/openzeppelin-contracts@v5.0.0...v5.0.2)
---
updated-dependencies:
- dependency-name: "@openzeppelin/contracts" dependency-type: direct:development
Fixes #
**Checklist**
=> build(deps-dev): Bump @openzeppelin/contracts from 5.0.0 to 5.0.2

package-lock.json, package.json
Bump 0.8.0-rc1
**Related issue(s)**: #711
**Checklist**
=> docs(update): bump 0.8.0-rc1

test/solidity/block/BlockInfo.js
Re-enable tests
Fixes #721 
**Checklist**
=> fix: Turning on test now that mirror node issue #7036 is fixed.

.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/dapp-playground-workflow.yml, .github/workflows/flow-pr-title-check.yml, .github/workflows/foundry_test.yml, .github/workflows/manual-testing.yml, .github/workflows/release-production.yml, .github/workflows/solidity-tests.yml, .github/workflows/system-contract-dapp.yml, .github/workflows/test-workflow.yml, .github/workflows/tests.yml
Updated the actions to conform to CI best practices
Fixes #741
=> ci: Update workflows for GHA best practices

contracts/hts-precompile/HederaAccountService.sol, contracts/hts-precompile/IHederaAccountService.sol
Add Solidity files for supporting the Hedera Account Service system contract
=> chore: add Solidity files for the Hedera Account Service

tools/analysis/README.md, tools/analysis/maian/README.md, tools/analysis/maian/signing_transactions.md, tools/analysis/manticore/README.md, tools/analysis/manticore/docker-compose.yaml, tools/analysis/slither/Dockerfile, tools/analysis/slither/README.md, tools/analysis/slither/detectors/hedera/ecrecover_usage_local.py, tools/analysis/slither/docker-compose.yaml
Analytical tools overview documentation.
=> docs: tools analysis reports

tools/analysis/slither/README.md
=> docs: Additional Slither AST note

contracts-abi/contracts/cancun/kzg-point-evaluation/KZGPointEvaluation.sol/KZGPointEvaluation.json, contracts/cancun/kzg-point-evaluation/KZGPointEvaluation.sol, test/cancun/kzg-point-evaluation/KZGPointEvaluation.js, test/constants.js
This PR adds coverage for HIP-867, KZG Point Evaluation Precompile. New wrapper contract + its artifacts + associated tests are included.
Fixes #821
**Checklist**
=> feat: added coverage for HIP-867 

package-lock.json, package.json
Bump 0.10.0-SNAPSHOT
**Related issue(s)**: #850 
Fixes #
**Checklist**
=> docs: Bump 0.10.0-SNAPSHOT

package-lock.json, package.json
Bump v0.9.0
**Related issue(s)**: #850 
Fixes #
**Checklist**
=> docs: Bump v0.9.0

contracts/system-contracts/hedera-token-service/HederaTokenService.sol
Add @dev comments to document behavior which reverts calls when a HTS view function is not successful.
Fixes #8746
=> chore: add comments to document revert behavior in view functions

.github/workflows/dapp-playground-workflow.yml, .github/workflows/flow-pr-title-check.yml, .github/workflows/foundry_test.yml, .github/workflows/migration-testing.yml, .github/workflows/opcode-logger-testing.yml, .github/workflows/pr-label-milestone-check.yml, .github/workflows/release-automation.yml, .github/workflows/release-production.yml, .github/workflows/solidity-tests.yml, .github/workflows/test-workflow.yml, .github/workflows/tests.yml
Update workflows to use latitude.sh based runners.
- Fixes #906
=> ci: update workflows to use latitude.sh based runners

.github/workflows/solidity-tests.yml, .github/workflows/test-workflow.yml, .github/workflows/tests.yml
Updating some of the actions in the workflows to use the step-security maintained version.
Fixes #923 
**Checklist**
=> ci: Updating workflows/actions to use the step-security version.

.github/workflows/migration-testing.yml
The migration workflow can't be executed due
```
Error: The action 'Start the local node with N:0.52.0, M:0.112.1, R:0.54.4' has timed out after 5 minutes.
```
Fixes #953
**Checklist**
=> feat: fix migration flow

.github/workflows/release-automation.yml
**Description**:  
The current release automation workflow is failing at the following steps:
- Checking out the repository
- Bumping the version
- Committing and tagging
- Creating a pull request
This PR aims to fix the release workflow and improve the output results.
**Related issue(s)**: 
Fixes #968 
**Checklist**
=> fix: updated release automation workflow

.github/CODEOWNERS, .github/workflows/release-automation.yml
- cherry picked #969 and #976 to release/0.10
- clean up release/0.10
=> chore: cherry picked #969 and #976 to release/0.10

.github/workflows/dapp-playground-workflow.yml, .github/workflows/flow-pr-title-check.yml, .github/workflows/foundry_test.yml, .github/workflows/migration-testing.yml, .github/workflows/opcode-logger-testing.yml, .github/workflows/pr-label-milestone-check.yml, .github/workflows/release-production.yml, .github/workflows/solidity-tests.yml, .github/workflows/test-workflow.yml, .github/workflows/tests.yml
Add "contents" persmission and add hardened runner step
Fixes #990 
**Checklist**
=> ci: Add "contents" persmission and add hardened runner step

.github/workflows/foundry_test.yml, .github/workflows/migration-testing.yml, .github/workflows/opcode-logger-testing.yml, .github/workflows/test-workflow.yml
Update per Q3 audit findings
Fixes #872 
This is a copy of PR #998. It was closed due to unsigned commits.
**Checklist**
=> ci: Update per Q3 audit findings

tools/erc-repository-indexer/docs/registry_design.md, tools/erc-repository-indexer/erc-contract-indexer/README.md, tools/erc-repository-indexer/erc-contract-indexer/package.json, tools/erc-repository-indexer/erc-contract-indexer/src/index.ts, tools/erc-repository-indexer/erc-contract-indexer/src/services/registryGenerator.ts, tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
- adds a main runner class as the entry point for the indexing tool.  
- updates the class diagram in the design document to more accurately reflect the tool's interface.  
- adds a README file providing an overview of the tool and instructions for starting it.  
Fixes #1042 
This PR builds upon the changes introduced in PR https://github.com/hashgraph/hedera-smart-contracts/pull/1057. As a result, many updates from PR https://github.com/hashgraph/hedera-smart-contracts/pull/1057 are reflected here.  
It is recommended to review PR https://github.com/hashgraph/hedera-smart-contracts/pull/1057 before proceeding with this one.
**Checklist**
=> feat: added a main runner class as the entry point for the indexing tool

.github/workflows/erc-registry-indexer.yml
This PR updates the ERC registry workflow to create a PR in the MNE repository whenever new ERC records are detected.
Fixes #1128 
**Checklist**
=> chore: updated erc-registry workflow to create PR to MNE repo

.github/workflows/flow-pr-title-check.yml
Fix check for forked repository on PR
Fixes #1152 
**Checklist**
=> ci: fixed check for forked repository on PR

.github/workflows/manual-testing.yml, .github/workflows/tests.yml
This PR adds a CI workflow for HIP904 tests as well as the manual testing workflow
Closes #1170 
**Checklist**
=> feat: adds CI workflows for HIP904 tests

contracts-abi/contracts/wrapped-tokens/WHBAR.sol/WHBAR.json, contracts/wrapped-tokens/README.md, contracts/wrapped-tokens/WHBAR.sol, test/wrapped-tokens/WHBAR.js
Address WHBAR audit comments.
Fixes #1145 
**Checklist**
=> feat: address WHBAR audit comments

contracts-abi/contracts/solidity/new/New.sol/Target.json, contracts-abi/contracts/wrapped-tokens/WHBAR.sol/WHBAR.json, contracts/solidity/new/New.sol, contracts/wrapped-tokens/README.md, contracts/wrapped-tokens/WHBAR.sol, test/constants.js, test/solidity/new/New.js, test/wrapped-tokens/WHBAR.js
There's some missing error handling on the transfer logic
**Solution**:
Add require check post transfer
Fixes #1241 
**Checklist**
=> feat: add require check post transfer on WHBAR.sol

package-lock.json, package.json, test/system-contracts/hedera-token-service/hrc-904/AirdropContract.js, test/system-contracts/hedera-token-service/hrc-904/CancelAirdropContract.js
Since 0.59.0 is released, this test should now pass
Fixes #1191 
**Checklist**
=> feat: Removes skipped test from AirdropContract.js

contracts/wrapped-tokens/WHBAR.sol, test/wrapped-tokens/WHBAR.js
Add an additional check on transfer to throw an error if the receiver is the whbar contract itself.
Fixes #1145 
**Checklist**
=> chore: update WHBAR contract

contracts/wrapped-tokens/README.md
Add note to the WHBAR doc.
Fixes #1145
**Checklist**
=> feat: update `WHBAR` readme

lib/layer-zero/HTSConnector.sol
There is no check for the max int64 amount value in `_debit` and `_credit` in the HTSConnector contract.
Fixes #1030
The task is requested after the contract audit.
**Checklist**
=> feat: add an addition check on the `HTSConnector` contract under the `layer-zero` example

.github/workflows/flow-pr-title-check.yml
Updates uses: step-security/conventional-pr-title-action to fix bug in 3.2.0
Fixes #1322
=> fix: Update flow-pr-title-check.yml

.github/workflows/erc-registry-indexer.yml
This PR fixed gpg signature for registry indexer
Fixes https://github.com/hashgraph/hedera-smart-contracts/issues/1388
**Checklist**
=> fix: fixed gpg signature for registry indexer

hardhat.config.js, package.json, test/openzeppelin/ERC-20/ERC20.js, utils/constants.js
=> Only erc20 tests v2

scripts/offchain-signed-tx-executor-cron/.env.example, scripts/offchain-signed-tx-executor-cron/.gitignore, scripts/offchain-signed-tx-executor-cron/README.md, scripts/offchain-signed-tx-executor-cron/cron.js, scripts/offchain-signed-tx-executor-cron/package-lock.json, scripts/offchain-signed-tx-executor-cron/package.json, scripts/offchain-signing/.env.example, scripts/offchain-signing/.gitignore, scripts/offchain-signing/README.md, scripts/offchain-signing/package-lock.json, scripts/offchain-signing/package.json, scripts/offchain-signing/scripts/signAccountDeleteTransaction.js
Currently, there are some off-chain signing scripts that live only on a branch (https://github.com/hiero-ledger/hiero-json-rpc-relay/tree/2648-add-offchain-signing-mechanism). They might be useful for some users, so we must push them into main.
Context - https://github.com/safe-global/safe-singleton-factory/issues/206
Fixes #1429 
**Checklist**
=> feat: add offchain signing script and cron

contracts-abi/contracts/openzeppelin/governor/ExampleGovernor.sol/ExampleGovernor.json, test/system-contracts/hedera-token-service/hrc-904/ClaimAirdropContract.js, test/system-contracts/hedera-token-service/utils.js
Currently, we don't have enough negative tests for HIP-904. The tests added in this PR are described in the linked issue.
Fixes #1449 
**Checklist**
=> feat: add negative tests for HIP-904
