hts-precompile/ExpiryHelper.sol
hts-precompile/FeeHelper.sol
hts-precompile/HederaTokenService.sol
hts-precompile/IHederaTokenService.sol
hts-precompile/KeyHelper.sol
hts-precompile/TokenCreateContract.sol

This PR updates the Solidity files `IHederaTokenService.sol` and `HederaTokenService.sol` with the most recent changes from HIP-358. It also adds new Solidity files that may serve as examples for token creation through the precompile contract:
* `KeyHelper.sol`, `FeeHelper.sol` and `ExpiryHelper.sol` contain helper methods 
*  `TokenCreateContract.sol` contains example methods for creating fungible and non-fungible tokens (both without and with fees) using the above mentioned helper contracts

Update Solidity files for HIP-358 (token create through the precompile)

---

hts-precompile/HederaTokenService.sol
hts-precompile/IHederaTokenService.sol

Add the missing Allowance/Approval methods that can be accessed via
the ERC-20 proxy that is not available in the HTS precompile.
Fixes #6
**Checklist**

Add Allowance/Approval methods to HTS precompile

---

hts-precompile/HederaTokenService.sol

The fungible allowance needs to return the number of tokens remaining.
Signed-off-by: Danno Ferrin <danno.ferrin@hedera.com>
for #6
**Checklist**

Add return value to fungible allowance

---

util-precompile/IPrngSystemContract.sol
util-precompile/PrngSystemContract.sol

Signed-off-by: Neeharika-Sompalli <neeharika.sompalli@hedera.com>
As per the [HIP-351](https://hips.hedera.com/hip/hip-351) , added `Prng` Precompiles in the name `IPrngSystemContract.sol` and `PrngSystemContract.sol`
Fixes #31

Add `Prng`Util Precompiles

---

exchange-rate-precompile/ExchangeRatePrecompile.sol
exchange-rate-precompile/IExchangeRate.sol
exchange-rate-precompile/SelfFunding.sol
util-precompile/PrngSystemContract.sol

Signed-off-by: Neeharika-Sompalli <neeharika.sompalli@hedera.com>
Fixes #45 
As per [HIP-475](https://hips.hedera.com/hip/hip-475) Adds `ExchangeRatePrecompile.sol`, `SelfFunding.sol`, and `IExchangeRate.sol` system precompiles

Add `ExchangeRatePrecompile` system precompiles

---

hts-precompile/HederaTokenService.sol
hts-precompile/IHederaTokenService.sol

Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>
Update the types for maxSupply and initialSupply to match the types in the protobuf specification.
Fixes #56 
**Checklist**

update types for maxSupply to int64 and initialSupply to uint64

---

contracts/hts-precompile/HederaTokenService.sol
contracts/hts-precompile/IHederaTokenService.sol

* Adds `transferFrom` and `transferFromNFT` (equivalents of ERC20/721 `transferFrom`) to `IHederaTokenService`.
Fixes #70

Add `transferFrom` support in `IHederaTokenService`

---

contracts/hts-precompile/ExpiryHelper.sol
contracts/hts-precompile/FeeHelper.sol
contracts/hts-precompile/HederaResponseCodes.sol
contracts/hts-precompile/HederaTokenService.sol
contracts/hts-precompile/KeyHelper.sol
contracts/hts-precompile/examples/token-create/TokenCreateContract.sol
contracts/hts-precompile/examples/token-manage/TokenManagementContract.sol
contracts/hts-precompile/examples/token-query/TokenQueryContract.sol
contracts/hts-precompile/examples/token-transfer/TokenTransferContract.sol

Signed-off-by: georgi-l95 <glazarov95@gmail.com>
Clean up dependencies of hts-precompile modules to reduce unnecessary coupling and fix some warnings about visibility modifiers.
The PR modifies the hts-precompile contracts to:
- Reduce coupling between helpers
- Changes `HederaResponseCodes` to a library
- Makes all hts-precompile contracts abstract
- Changes the visibility of `FeeHelper` to pure to silence compiler warnings.
- Bump hedera local-node version
- Bump hardhat-chai-matchers version
None
Original [PR](https://github.com/hashgraph/hedera-smart-contracts/pull/83)
**Checklist**

Resolve coupling and clean contracts

---

contracts/hts-precompile/HederaTokenService.sol
contracts/hts-precompile/examples/token-create/TokenCreateContract.sol
contracts/hts-precompile/examples/token-manage/TokenManagementContract.sol
contracts/hts-precompile/examples/token-query/TokenQueryContract.sol
test/hts-precompile/erc-721/ERC721Contract.js
test/hts-precompile/utils.js

Signed-off-by: georgi-l95 <glazarov95@gmail.com>
Changed functions perform critical operations that change token state. If they are left external, it would allow anyone to cause very serious issues if the inheriting contract has the ADMIN, KYC, or PAUSE keys for Hedera token[s].
In your tutorials, devs are suggested to inherit these HTS contracts. If they decide to make the inheriting contract have the admin key to allow it to change the token's certain properties behind restricted functions, anyone can bypass the restrictions via the inherited HTS contract, and hijack the token. Or if they make the inheriting contract have the pause key and make it algorithmically manage the pause state of the token, anyone can bypass such algorithm and DOS the token. Given the expected …

Critical HTS functions marked external

---

test/hts-precompile/token-transfer/tokenTransferContract.js

Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>
Write tests to show that the transferFrom function does not allow the caller to transfer fungible or non-fungible tokens without approval.
Fixes #133

Tests to show system HTS contract transferFrom does not work without approval

---

test/hts-precompile/token-managment/tokenManagmentContract.js

Signed-off-by: georgi-l95 <glazarov95@gmail.com>
Fix `updateTokenInfo` test. Treasury needed to be changed to the admin account. We were trying to set it to the contractId, while signing with signers[0].
Fixes #147 
**Checklist**

Fix `updateTokenInfo` test in Token Management Tests

---

utils/constants.js

**Description**: This PR fixed the bug where the compile command from Hardhat is blocked by requiring Hedera operator keys be set
Fixes #293 
**Checklist**

fix: unblocked compile command from requiring env variables be set (#293)

---

system-contract-dapp-playground/__tests__/ethers/index.test.ts
system-contract-dapp-playground/src/api/ethers/index.ts
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/BalanceOf.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Mint.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenInformation.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/TokenPermissions.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/Transfer.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/index.tsx
system-contract-dapp-playground/src/types/interfaces.d.ts

To interact with on-chain contracts, baseContract is needed not contractFactory
**Description**: This PR reworked the logic for the getContractFactory function to generate a new BaseContract type instance and redistribute it to the child components of the contract-interaction
Fixes #330 
**Checklist**

fixed: fixed contract types for contract interaction logic (#330)

---

test/hts-precompile/token-create/tokenCreateCustomContract.js

**Description**: This PR contains two unit tests to make sure that the caller's public key needs to be set as the `key` param for the create token functions
Fixes #342
**Checklist**

test: added unit tests to fix #342

---

system-contract-dapp-playground/__tests__/hedera/helper/index.test.ts
system-contract-dapp-playground/__tests__/hedera/hts-interactions/index.test.ts
system-contract-dapp-playground/src/api/hedera/tokenCreateCustom-interactions/index.ts
system-contract-dapp-playground/src/types/contract-interactions/HTS/index.d.ts
system-contract-dapp-playground/src/utils/contract-interactions/HTS/constant.ts
system-contract-dapp-playground/src/utils/contract-interactions/HTS/helpers.ts

This PR adds a set of APIs and unit tests to support facilitating interacting with TokenCreateCustom contract. The methods exposed in this PR are
- createFungibleTokenPublic()
- createFungibleTokenWithCustomFeesPublic()
- createNonFungibleTokenPublic()
- createNonFungibleTokenWithCustomFeesPublic()
In addition, this PR also adds a couple of quick helper functions constructIHederaTokenKey() and prepareHederaTokenKeyArray() to help constructing an array of keys to assign to the token during creation
Fixes partial #316
**Checklist**

feat: Added API and unit tests to facilitate fungible and non-fungible token creations for TokenCreateCustom contract

---

system-contract-dapp-playground/__tests__/hedera/hts-interactions/index.test.ts
system-contract-dapp-playground/src/api/hedera/tokenCreateCustom-interactions/index.ts
system-contract-dapp-playground/src/types/contract-interactions/HTS/index.d.ts

This PR adds a set of APIs and unit tests to support facilitating interacting with TokenCreateCustom contract. The methods exposed in this PR are
- mintTokenPublic()
- mintTokenToAddressPublic()
- mintNonFungibleTokenToAddressPublic()
- associateTokenPublic
- associateTokensPublic()
- grantTokenKycPublic()
Fixes partial #316
**Checklist**

feat: Added API and unit tests to facilitate token mint, token associating, and granting kyc for TokenCreateCustom contract

---

system-contract-dapp-playground/__tests__/hedera/hts-interactions/token-query-contract/index.test.ts
system-contract-dapp-playground/src/api/hedera/tokenQuery-interactions/index.ts
system-contract-dapp-playground/src/types/contract-interactions/HTS/index.d.ts
system-contract-dapp-playground/src/utils/contract-interactions/HTS/helpers.ts

**Description**:  finished integrating API methods for TokenQueryContract
Fixes partial #318 
**Checklist**

dapp-feat: finished integrating API methods for TokenQueryContract

---

system-contract-dapp-playground/__tests__/hedera/hts-interactions/token-query-contract/index.test.ts
system-contract-dapp-playground/src/api/hedera/tokenQuery-interactions/index.ts
system-contract-dapp-playground/src/types/contract-interactions/HTS/index.d.ts
system-contract-dapp-playground/src/utils/contract-interactions/HTS/helpers.ts

**Description**: 
This PR adds a couple of helper functions to help convert Proxy object returned from contract calls to regular TypeScript object for the APIs in tokenQueryGeneralInfo group. By doing this enables to ability to cache the token info object into localStorage.
Fixes partial #318
**Checklist**

dapp-feat: added helper functions to help convert Proxy object into regular Typescript object for token query general information

---

system-contract-dapp-playground/.prettierrc
system-contract-dapp-playground/src/api/localStorage/index.ts
system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/AssociateHederaToken.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/FungibleTokenCreate.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/GrantTokenKYC.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/MintHederaToken.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-create-custom/methods/NonFungibleTokenCreate.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenDelete/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenInfo/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenPermission/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenRelation/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenStatus/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-management-contract/methods/manageTokenSupplyReduction/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/querySpecificToken/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenGeneralInfo/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenPermission/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenStatus/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-query-contract/methods/queryTokenValidity/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-transfer-contract/method/transferCrypto/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-transfer-contract/method/transferMultipleTokens/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/token-transfer-contract/method/transferSingleToken/index.tsx
system-contract-dapp-playground/src/components/navbar/index.tsx
system-contract-dapp-playground/src/components/wallet-popup/index.tsx
system-contract-dapp-playground/src/utils/common/constants.ts
system-contract-dapp-playground/src/utils/common/helpers.ts

This PR completes the Wipe Cached Transaction Results feature
Fixes #390 
** UI demo **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/6c6071db-d850-415e-b4d6-9e37e36cc5a4
**Checklist**

dapp-feat: Wipe Cached Transaction Results feature complete (#390)

---

system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/token-information/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/token-permission/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/approve/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/owner-of/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/token-information/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/token-uri/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/shared/hooks/useRetrieveMapValueFromLocalStorage.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/shared/hooks/useUpdateMapStateUILocalStorage.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleAPIErrors.tsx
system-contract-dapp-playground/src/components/contract-interaction/hts/shared/methods/handleRetrievingTransactionResultsFromLocalStorage.tsx
system-contract-dapp-playground/src/components/contract-interaction/index.tsx
system-contract-dapp-playground/src/components/navbar/index.tsx
system-contract-dapp-playground/src/components/wallet-popup/index.tsx
system-contract-dapp-playground/src/sections/landing/index.tsx
system-contract-dapp-playground/src/utils/common/constants.ts
system-contract-dapp-playground/src/utils/contract-interactions/erc/erc721/constant.ts

- complete ERC721 TokenPermission feature
- added HEDERA_COMMON_WALLET_REVERT_REASONS constant object for different revert reasons returned from wallet
Fixes partial #322 
**UI Demo**
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/daabfa14-d892-4945-9cf9-9646b9f8518c
**Checklist**

dapp-feat: ERC721 TokenPermission feature complere

---

system-contract-dapp-playground/src/api/hedera/erc721-interactions/index.ts
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-20/methods/token-permission/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/operator-approve/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/erc-721/methods/token-transfer/index.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/shared/hooks/useUpdateMapStateUILocalStorage.tsx
system-contract-dapp-playground/src/components/contract-interaction/erc/shared/methods/common.tsx
system-contract-dapp-playground/src/utils/common/constants.ts
system-contract-dapp-playground/src/utils/contract-interactions/erc/erc721/constant.ts

- ERC721 Approval feature complete
- ERC721 TransferFrom feature complete
Fixes #322
** UI Demo **:
https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/d649fbff-2ebe-4c4b-b8c8-543ce4116ffa
**Checklist**

dapp-feat: ERC721 Approval and TransferFrom feature complete

---

system-contract-dapp-playground/package-lock.json
system-contract-dapp-playground/package.json
system-contract-dapp-playground/src/sections/activity/index.tsx
system-contract-dapp-playground/src/types/contract-interactions/shared/index.d.ts
system-contract-dapp-playground/src/utils/common/helpers.ts

- revised the logic for deleting transactions in the main activity page. Prior to this update, users had the option to click on individual delete buttons next to each transaction to remove a specific transaction, or they could delete all transactions at once by clicking on the 'Remove all transactions' button. Now, individual delete buttons are replaced with checkboxes, enabling users to select multiple transactions at once and perform desired actions on them. Additionally, the 'Remove all transactions' button is replaced with 'Remove selected transactions,' allowing users to delete transactions that have their checkboxes checked.
- finished the new exporting transactions to CSV feature. Users now have the ability to select the transactions they want to export. The new …

dapp-feat: Export Transaction to CSV feature complete (#421)

---

contracts/solidity/units/cryptoUnits.sol
contracts/solidity/units/timeUnits.sol
test/constants.js
test/solidity/units/cryptoUnits.js
test/solidity/units/timeUnits.js

Adding unit tests for Solidity Crypto Units and Time Units
**Related issue(s)**: https://github.com/hashgraph/hedera-smart-contracts/issues/428
Fixes #

Adding unit tests for Solidity Crypto Units and Time Units

---

.gitignore
contracts/solidity/concatenation/Concatenation.sol
test/constants.js
test/solidity/concatenation/concatenation.js

Adding tests for Concatenation.
https://github.com/hashgraph/hedera-smart-contracts/issues/441
Fixes #

Adding tests for Concatenation.

---

.gitignore
contracts/solidity/transaction/MessageFrameAddresses.sol
contracts/solidity/transaction/Secondary.sol
contracts/solidity/transaction/Transaction.sol
test/constants.js
test/solidity/transaction/transaction.js

Add support for transaction properties
https://github.com/hashgraph/hedera-smart-contracts/issues/431
Fixes #

Adding tests for the Transactions in Solidity

---

.github/workflows/solidity-tests.yml

Github action for soldiity test is broken with bad yaml
- encase test tag for fix yaml format
- make action a `workflow_call` to have it run on call not automatically
Fixes #468 
**Checklist**

Fix Solidity Github action

---

contracts/solidity/new/New.sol
test/constants.js
test/solidity/new/New.js

- added new New.sol contract to showcase the `new` keyword usage
- added unit tests for New.sol
**Related issue(s)**: #450
Fixes #450
**Checklist**

feat: added new contract to demonstrate `new` keyword usage (#450)

---

contracts/solidity/address/Address.sol
contracts/solidity/address/Recipient.sol
test/constants.js
test/solidity/address/address.js

Tests for Address operations added.
https://github.com/hashgraph/hedera-smart-contracts/issues/445

Tests for Address operations

---

contracts/solidity/inhetitance/Base.sol
contracts/solidity/inhetitance/Main.sol
test/constants.js
test/solidity/inheritance/inheritance.js

Adding tests for inheritance
[[Solidity Support] Inheritance operations#446](https://github.com/hashgraph/hedera-smart-contracts/issues/446)

Adding tests for inheritance

---

contracts/solidity/functions/Functions.sol
contracts/solidity/functions/FunctionsChild.sol
contracts/solidity/functions/FunctionsParent.sol
test/constants.js
test/solidity/address/address.js
test/solidity/concatenation/concatenation.js
test/solidity/encoding/Encoding.js
test/solidity/errors/errors.js
test/solidity/functions/functions.js
test/solidity/inheritance/inheritance.js
test/solidity/new/New.js
test/solidity/units/cryptoUnits.js
test/solidity/units/timeUnits.js

Problem
The Hedera network supports solidity as one of the smart contracts development languages.
Occasionally items have shown up that surfaced in-equivalence at the language layer.
Solution
Add support for Function calls operations
https://github.com/hashgraph/hedera-smart-contracts/issues/449

Adding tests for functions.

---

contracts/solidity/address/AssemblyAddress.sol
test/constants.js
test/solidity/address/AssemblyAddress.js

- Added a new Solidity contract to demonstrate assembly address operations, including `extcodesize`, `extcodehash`, and `extcodecopy`.
- Included unit tests to verify the functionality of the contract.
**Related issue(s)**: #459
Fixes #459
**Checklist**

feat: added new contract to showcase assembly address operations (#459)

---

contracts/solidity/cryptomath/Arithmetic.sol
test/constants.js
test/solidity/cryptomath/CryptoMath.js
test/solidity/cryptomath/arithmetic.js
utils/helpers.js

Adding tests for Arithmetic
https://github.com/hashgraph/hedera-smart-contracts/issues/473

Adding tests for Arithmetic

---

package.json
test/foundry/mocks/hts-precompile/HtsSystemContractMock.sol

This PR adds the `test/foundry/mocks` folder to enable the use of the system contract mocks in a hardhat project that installs the hedera-smart-contracts as a dependency.
It also adds a `TokenCreated` event which is emitted by the `HtsSystemContractMock` contract when a `HederaFungibleToken` or  `HederaNonFungibleToken` contract is created, to make it easier to determine the address of the token contract in a hardhat development environment.
Fixes #
**Checklist**

Update files to include mocks

---

.gitignore
contracts/solidity/defaults/Defaults.sol
test/constants.js
test/solidity/defaults/defaults.js

Adding tests for the default values of all types in Solidity
https://github.com/hashgraph/hedera-smart-contracts/issues/471

Adding tests for the default values of all types in Solidity

---

contracts/solidity/errors/Errors.sol
contracts/solidity/errors/ErrorsExternal.sol
test/constants.js
test/solidity/errors/errors.js

Adding tests for advance errors
https://github.com/hashgraph/hedera-smart-contracts/issues/480

Adding tests for advance errors

---

contracts/solidity/payment-channel/PaymentChannel.sol
test/solidity/payment-channel/PaymentChannel.js
test/solidity/payment-channel/helper.js

- added a new PaymentChannel contract
- added PaymentChannelHelper class to sign payment message off-chain
- added a suite of unit tests to cover PaymentChannel contract
**Related issue(s)**: #493 
Fixes #493 
**Checklist**

feat: added PaymentChannel smart contract (#493)

---

contracts/solidity/modular/Token.sol
test/solidity/modular/Token.js

- added Token modular contract to showcase in-line assembly math operations
- added unit tests to cover Token modular contract
**Related issue(s)**: #494
Fixes #494
**Checklist**

feat: added modular solidity example contract (#494)

---

contracts/yul/math-coverage/MatchCoverage.sol
test/yul/math-coverage/MathCoverage.js

- added MathCoverage contract to cover below opcodes
- added unit tests to cover MathCoverage cotract
**Related issue(s)**: #511
Fixes #511
**Checklist**

feat: added math coverage solidity example contract (#511)

---

contracts/yul/bitwise-coverage/Bitwise.sol
test/yul/bitwise-coverage/Bitwise.js

- added Bitwise contract to cover below opcodes
- added unit tests to cover Bitwise cotract
**Related issue(s)**: #519
Fixes #519
**Checklist**

feat: added bitwise coverage solidity example contract (#519)

---

contracts/yul/data-allocation/DataAllocation.sol
test/yul/data-allocation/DataAllocation.js

- added DataAllocation solidity example contract to cover below opcodes
- added unit tests to cover DataAllocation contract
**Related issue(s)**: #520
Fixes #520
**Checklist**

feat: added DataAllocation solidity example contract

---

contracts/solidity/account/NonExisting.sol
contracts/solidity/account/NonExtDup.sol
test/constants.js
test/solidity/account/nonExisting.js

Adding tests for NonExistant account
https://github.com/hashgraph/hedera-smart-contracts/issues/482

Adding tests for NonExistant account

---

contracts/solidity/control/ControlStructures.sol
test/constants.js
test/solidity/control/control.js

This PR adds:
* New contract with functions to test control structures
* New test file for testing this contract
Fixes #448 

Adds tests for control structures

---

contracts/solidity/control/ControlStructures.sol
test/solidity/control/control.js

This PR renamed the methods in ControlStructures contract by replacing the special keyword "test" with "evaluate" so that the `forge test` wouldn't pick up these methods hence wouldn't cause disruptions in foundry-test CI 
Fixes #566
**Checklist**

update: renamed methods in ControlStructures contract (#566)

---

contracts/solidity/assignments/AssignmentReferenceTypes.sol
contracts/solidity/assignments/DestructuringReturns.sol
test/constants.js
test/solidity/assignments/assignments.js

* Adds contract for destructuring return values
* Adds contract for assignment of reference types
* Adds test for abovementioned contracts
Fixes #470

Adds tests for parameter restructuring and assignment

---

contracts/solidity/errors/Errors.sol
contracts/solidity/oz/ERC-2981/ERC2981.sol
test/solidity/oz/erc2981/erc2981.js

Adding tests for ERC-2981
Add OZ ERC 2981 example #552

Adding tests for [OZ] ERC-2981

---

contracts/solidity/errors/Panic.sol
test/constants.js
test/solidity/errors/panicErrors.js

Creates tests to check panic errors support
Fixes #483

Creates tests for panic errors support

---

contracts/solidity/modifiers/A.sol
contracts/solidity/modifiers/B.sol
contracts/solidity/modifiers/DerivedContract.sol
contracts/solidity/modifiers/Modifiers.sol
test/solidity/modifiers/Modifiers.js

Solidity modifiers coverage
Fixes #487

487 Solidity Support Modifiers

---

contracts/yul/contract-caller/ContractCaller.sol
contracts/yul/math-coverage/MatchCoverage.sol
test/yul/contract-caller/ContractCaller.js

- added ContractCaller solidity example contract to cover 
- added unit tests to cover ContractCaller contract
Fixes #534 
**Checklist**

feat: added ContractCaller solidity example contract (#534)

---

contracts/evm/Precompiles.sol
package-lock.json
package.json
test/evm/Precompiles.js

EVM Precompiles support.
Fixes #496

EVM Precompiles support

---

contracts/solidity/errors/Panic.sol
test/solidity/errors/panicErrors.js

This PR renamed the methods in Panic contract by replacing the special keyword "test" with "verify" so that the forge test wouldn't pick up these methods hence wouldn't cause disruptions in foundry-test CI
Fixes #578 
**Checklist**

update: renamed methods in Panic contract to fix foundry-test in CI (#578)

---

TEST_SETUP.md
hardhat.config.js
utils/constants.js

Adding Besu local node configuration.
This is just for convenience of the user.
Currently we have in our hardhat.config.js configurations for 3 networks. (local, testnet, previewnet)
This task is going to add a 4th one. For a Local Besu instance (if the user of the repo has one)
This local Besu instance is useful for debugging when a problem with our Local Node is identified. 
You can double check our smart contract tests against the pure Besu node. 
Add Besu local node configuration #616

feat: Adding besu local node config

---

contracts/oz/access-control/AccessControlContract.sol
test/OZ/access-control/accessControl.js

OpenZeppelin Access control example.  Depends on the merge of local node PR [457](https://github.com/hashgraph/hedera-local-node/pull/457) and its adoption in the local node.
Fixes #539

feat: added OZ Access control example (#539)

---

.github/workflows/manual-testing.yml
.github/workflows/test-workflow.yml
package-lock.json
package.json
test/multicall/Multicall.js

This PR aims to add manual workflow, which can be triggered by specifying tag which the tests should run against.
Fixes #648 
**Checklist**

feat: add workflow which allows to start tests against desired tag

---

test/hts-precompile/utils.js
utils/constants.js

Updates the `networkNodeUrl` and `mirrorNode` constant values. The SDK doesn't parse DNS url but IP addresses.
Fixes #651
**Checklist**

fix: fixed networkNodeUrl and mirrorNode constant values

---

hardhat.config.js
test/solidity/voting/Ballot.js
utils/constants.js

"Removed the ZeroHash instances as private keys within the `PRIVATE_KEYS` constant variable. It is not mandatory for the `PRIVATE_KEYS` constant variable to contain exactly six private keys for the process to proceed. Attempting to fill the empty slots in the `PRIVATE_KEYS` variable will result in a `Private keys invalid` error."
Fixes #652 
**Checklist**

fix: removed ZeroHashes as private keys

---

hardhat.config.js

Removed gas config in hardhat.config.js 
Fixes #392 
**Checklist**

fix: removed gas config in hardhat.config.js (#392)

---

test/openzeppelin/ERC-1155/ERC1155.js
test/openzeppelin/ERC-1155/ERC1155Token.js

Removed custom gas limit for ERC1155.
Fixes #394 
**Checklist**

fix: removed custom gas limit for ERC1155 deploy transaction (#394)

---

contracts-abi/contracts/discrepancies/nonce/InternalCallee.sol/InternalCallee.json
contracts-abi/contracts/discrepancies/nonce/InternalCaller.sol/InternalCaller.json
contracts-abi/contracts/hts-precompile/examples/token-create/TokenCreateCustom.sol/TokenCreateCustomContract.json
contracts-abi/contracts/multicaller/Receiver.sol/Receiver.json
contracts-abi/contracts/multicaller/Reverter.sol/Reverter.json
contracts-abi/contracts/openzeppelin/beacon-proxy/MyProxy.sol/MyProxy.json
contracts-abi/contracts/solidity/precompiles/Precompiles.sol/Precompiles.json
contracts/discrepancies/nonce/InternalCallee.sol
contracts/discrepancies/nonce/InternalCaller.sol
contracts/multicaller/Receiver.sol
contracts/multicaller/Reverter.sol
contracts/openzeppelin/beacon-proxy/MyProxy.sol
contracts/openzeppelin/reentrancy-guard/ReentrancyGuardTestSender.sol
contracts/solidity/block/BlockInfo.sol
contracts/solidity/errors/Panic.sol
contracts/solidity/precompiles/Precompiles.sol
contracts/solidity/scoping/Scoping.sol
test/multicall/Multicall.js
test/solidity/errors/panicErrors.js

- cleaned up all warnings thrown by Solidity after compilation. 
- fixed unit tests where needed
- there're only 4 warnings left but only because they serve the purpose of the coverages
```bash
Warning: This declaration shadows an existing declaration.
--> contracts/solidity/scoping/Scoping.sol:21:13:
|
21 |             uint x;
|             ^^^^^^
Note: The shadowed declaration is here:
--> contracts/solidity/scoping/Scoping.sol:18:9:
|
18 |         uint x = 1;
|         ^^^^^^
Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
--> contracts/discrepancies/nonce/InternalCallee.sol:27:9:
|
27 |         selfdestruct(_addr);
|         ^^^^^^^^^^^^
Warning: "selfdestruct" has been …
```

chore: cleaned up Solidity warnings

---

package-lock.json
package.json
test/hts-precompile/token-managment/tokenManagmentContract.js
test/hts-precompile/utils.js
test/safe-hts-precompile/SafeHTS.js

- Bumps the version of local-node to use the latest versions of the network and mirror nodes.
- Reorganizes some tests that were failing due to changes from [HIP 540](https://hips.hedera.com/hip/hip-540)
- Removed redundant steps from the test `SafeHTS -> should be able to transfer tokens and hbars atomically`.
Fixes #
**Checklist**

chore: bump local-node version

---

.github/workflows/flow-pr-title-check.yml
.github/workflows/solidity-tests.yml
.github/workflows/tests.yml

Update source of conventional-pr-title-action to use step-security's maintained version
Version 4 of upload-artifact action is currently not working on self-hosted runners, download-artifact has been showing the same behavior on version4. Reverted actions/download-artifact to version 3 to allow workflows to finish running
Fixes #784

ci: Updated source for conventional-pr-title-action

---

tools/analysis/slither/docker-compose.yaml

The path in docker compose was incorrect. Dockerfile is moved to the same directory where yaml is placed.
Fixes #
**Checklist**

fix(slither): setting the correct path to the build in dc cofnig

---

.github/workflows_documentation.md

Currently, there is a `README.md` file in the `.github` folder. This `.github/README.md` overlaps with the `README.md` in the root directory, which is displayed on the repository landing page. This PR is to rename the `.github/README.md` to resolve the issue.
Fixes #843

fix: renamed .github/README.md to ./github/workflows_documentation.md

---

.github/workflows/solidity-tests.yml
.github/workflows/tests.yml

Download artifact v4 is not compatible with upload artifact v3. A refactoring and update is needed to migrate from v3 to v4.
Currently just the download artifact action has been updated by dependabot. This is a temporary solution to repair the broken pipeline.
The proper fix of the problem is tracked via #812 
Fixes #
**Checklist**

chore: downgrade actions/download-artifact to v3.0.2

---

.github/workflows/release-production.yml
.github/workflows/solidity-tests.yml
.github/workflows/test-workflow.yml
.github/workflows/tests.yml

This PR migrates the `upload-artifact` and `download-artifact` actions from v3 to v4 in advance of the November deprecation of v3.
Fixes #812 
**Checklist**

chore: migrate artifact actions v3 to v4

---

contracts-abi/contracts/solidity/block/BlockInfo.sol/BlockInfo.json
contracts/solidity/block/BlockInfo.sol
test/solidity/block/BlockInfo.js

When retrieving in smart contracts, not all block properties match what's returned to hardhat. 
- Retrieving a blockhash through hardhat returns an actual hash value, but returning it from within a smart contract returns `0x0000000000000000000000000000000000000000000000000000000000000000`.
- Retrieving the block's coinbase returns a different value when called in the smart contract.
**Steps to reproduce**;
- The test `should be able to get the hash of a given block when the block number is one of the 256 most recent blocks` in `BlockInfo` reproduces the hash value issue. - fixed :white_check_mark: 
- The test `should get the current block miners address using block.coinbase` reproduces the coinbase issue. - not reproducible :x: 
Fixes #436 
**Notes …

feat: block properties behaviour

---

contracts/hip-719-proxy/HRC719TokenProxy.sol

This PR includes the HTS Token Proxy contract for reference.
Fixes #885.
**Checklist**

chore: add HTS Token Proxy reference contract

---

.github/workflows/foundry_test.yml
.github/workflows/migration-testing.yml
.github/workflows/opcode-logger-testing.yml
.github/workflows/test-workflow.yml

This PR migrates the foundry-toolchain action to the step-security maintained version
Fixes #869 
**Checklist**

chore: migrate foundry-toolchain to the step-security maintained version

---

contracts/system-contracts/hedera-account-service/HederaAccountService.sol
contracts/system-contracts/hedera-account-service/IHederaAccountService.sol

The HederaAccountService system contract files are missing the `isAuthorizedRaw` function definitions.

chore: add `isAuthorizedRaw` function

---

system-contract-dapp-playground/package-lock.json
system-contract-dapp-playground/package.json

For some reason, the `js-cookie` module is not listed in the root dependencies, but the `next build` command does not detect the missing package. This PR added the js-cookie to the package.
Fixes #925
**Checklist**

build(deps): installed js-cookie

---

.github/workflows/manual-testing.yml

There were issues with the workflow where acceptance-workflow was requesting further permissions and it would break:
[Link to issue](https://github.com/hashgraph/hedera-smart-contracts/actions/runs/10956339779/workflow). This should resolve that issue.
Fixes #955 
**Checklist**

ci: Adding further permissions to the manual-testing workflow as it was not running correctly.

---

.github/CODEOWNERS
.github/workflows/release-automation.yml

Updates are required on workflow permissions to enable the workflows to push directly to main as part of their standard process. This PR attempts to correct those permissions. Further, the PR pulls in standard updates to the CODEOWNERS file, adding `devops-ci` group and removing duplicate entries on lines.
**Related Issues**: #968

ci: Update Permissions on smart-contracts workflows to update main

---

test/network/key-rotation.js

There has been a report from a community member raising concerns about whether an account's EVM address would be modified or updated if the account's key is changed—for example, from one ECDSA key to another, or from ECDSA to ED25519. 
This PR addresses the concern and confirms that an account's EVM address is fixed at the time of creation and will remain unchanged, regardless of any updates to the account's key.
Fixes #983
**Example Log Output**:
```
Key Rotation Test Suite
>>>>>>> accountId_Alpha <<<<<<<
- accountId: 0.0.1044
- public key: 302d300706052b8104000a03220002f6de454684020fe47e85c225288b2caae36bae587c4c08d142cb2ca8177fe0f5
- evm address: 9b69fafd7574a2ef5635c7ebddc0e7258569076d
>>>>>>> accountInfoAfterKeyRotation - ECDSA <<<<<<<
- accountId: 0.0.1044
- public …
```

test: added test coverage to confirm key alias remain the same after key rotations

---

.github/scripts/check-pr.js

Applied the check-pr from the hedera-json-rpc-relay.
Fixes #981 
**Checklist**

feat: Skip issue matching for snyk and dependabot PRs.

---

.github/workflows/test-workflow.yml

The updated version of the action publish-unit-test-result in the workflow requires new inputs, this PR aims to fix that.
Additionally the attached issue to this PR aimed to see if we can have variable permissions based on how the workflow is run. However, I could not find a suitable solution for the moment and the only action that takes advantage of the extra permissions is publish-test-results so I see no security implications currently.
Fixes #957 
**Checklist**

ci: Updating one of the actions to fix issues with inputs.

---

.github/workflows/flow-pr-title-check.yml

Title check CI job fail for PRs that are from a forked repository due to the lack of the secret.GITHUB_TOKEN. This PR adds an option to skip the check if the PRs are from forked repos.
Fixes #999
**Checklist**

fix: skipped title check CI job for forked PRs

---

contracts-abi/contracts/system-contracts/hedera-account-service/examples/crypto-allowance/cryptoAllowance.sol/CryptoAllowance.json
contracts/system-contracts/hedera-account-service/HederaAccountService.sol
contracts/system-contracts/hedera-account-service/examples/crypto-allowance/cryptoAllowance.sol
test/system-contracts/hedera-account-service/crypto-allowance/cryptoAllowance.js

This PR adds e2e test coverage for isAuthorizedRaw() in HIP-632
Fixes #844
**Checklist**

test: added E2E coverage for `isAuthorizedRaw()` in HIP-632.

---

.github/workflows/dapp-playground-workflow.yml
.github/workflows/foundry_test.yml
.github/workflows/migration-testing.yml
.github/workflows/opcode-logger-testing.yml
.github/workflows/test-workflow.yml

This PR updates the references to node from v18 to v20.
Fixes #1008

chore: Upgraded references in github workflows

---

.github/workflows/release-automation.yml

The release-automation.yml workflow uses a release notes generator action that has an equivalent maintained by StepSecurity.
This PR replaces it with the StepSecurity variant.
Fixes #1018 
N/A
**Checklist**

ci: replace release notes generator action with one maintained by stepsecurity

---

.gitignore
tools/erc-repository-indexer/docs/registry_design.md

The ERC Registry is an initiative aimed at creating a comprehensive registry of contracts that are widely recognized and believed to be standard ERC token contracts with a high degree of confidence. At this early phase of the project, it requires a design document to highlight and outline the approach.
This PR adds a new design document for the approach.
**Related issue(s)**: #1028 
Fixes #1029

docs: added a design document outlining the ERC contract indexer

---

tools/erc-repository-indexer/erc-contract-indexer/src/services/config.ts
tools/erc-repository-indexer/erc-contract-indexer/src/services/registryGenerator.ts
tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
tools/erc-repository-indexer/erc-contract-indexer/tests/services/config.test.ts
tools/erc-repository-indexer/erc-contract-indexer/tests/services/registryGenerator.test.ts

This PR enhances `resolveStartingPoint()` by adding the ability to fetch the `next` pointer from disk. To support this, `RegistryGenerator()` has been updated with two new methods: `updateNextPointer()` and `retrieveNextPointer()`. 
The `resolveStartingPoint()` method now determines the starting point for indexing based on configuration settings. It prioritizes the `STARTING_POINT` defined in the configuration; if unavailable, it checks for a stored `next` pointer on disk and uses it if found. If neither is present, indexing defaults to starting from the genesis block.
Fixes #1056
**Checklist**

feat: added an option for resolveStartingPoint() to fetch next pointer from disk

---

tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-20.json
tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/erc-721.json
tools/erc-repository-indexer/erc-contract-indexer/erc-registry/mainnet/next-pointer.json
tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-20.json
tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/erc-721.json
tools/erc-repository-indexer/erc-contract-indexer/erc-registry/testnet/next-pointer.json

**Description**:  
This PR includes a collection of files containing token information for ERC-20 and ERC-721 tokens on the Hedera networks. It represents the final outcome of the ERC Registry project, which aims to index the entire network to identify ERC-20 and ERC-721 token contracts. The project also performs contract calls to the mirror node to retrieve detailed information about these tokens.  
Currently, this PR includes ERC contract data for both testnet and mainnet, up to 10/12/2024.
Fixes #1074 
**Checklist**

chore: added a list of files containing token information for ERC-20 and ERC-721 tokens on the Hedera networks

---

.github/workflows/erc-registry-indexer.yml
tools/erc-repository-indexer/erc-contract-indexer/README.md

This PR adds the `erc-registry-indexer.yml` file to enable the execution of the ERC registry project on dispatch. The workflow allows users to target any Hedera production network (previewnet, testnet, mainnet) and provide a mirror node base URL to index the targeted network for ERC-20 and ERC-721 tokens.
Once the workflow completes, if new ERC contracts are detected, it will automatically create a PR targeting `main` branch to capture the new records. Here is an example of the automatic PR: https://github.com/hashgraph/hedera-smart-contracts/pull/1099
Fixes #1081 
**Checklist**

chore: added a workflow script to enable the execution of the ERC registry project on dispatch

---

tools/erc-repository-indexer/erc-contract-indexer/package-lock.json
tools/erc-repository-indexer/erc-contract-indexer/package.json
tools/erc-repository-indexer/erc-contract-indexer/src/services/byteCodeAnalyzer.ts
tools/erc-repository-indexer/erc-contract-indexer/src/utils/constants.ts
tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/byteCodeAnalyzer.test.ts

This PR replaces the inefficient regex-based approach in the `isErc` method with the [**Aho-Corasick** algorithm](https://en.wikipedia.org/wiki/Aho%E2%80%93Corasick_algorithm), significantly improving performance when analyzing large bytecodes. Aho-Corasick is a string searching algorithm that builds a finite state machine for matching multiple patterns simultaneously. It processes the bytecode in linear time relative to the input size, ensuring drastically faster and more scalable analysis compared to the previous regex-based method.
- **Regex-based approach**: 20 KB bytecode takes more than 3600 ms.
- **Aho-Corasick**: The same bytecode processed in under 3 ms.
[A unit test](https://github.com/hashgraph/hedera-smart-contracts/pull/1121/files#diff-d0b505661019f6658e9c6294 …

fix: modified `isErc` for better performance in ERC Registry tool

---

.github/release.yml

This PR modified the .github/release.yaml to include `internal` and `github_action` labeled PRs
Fixes #1137
**Checklist**

fix: updated .github/release.yaml to include internal and github_action labeled PRs 

---

.github/workflows/erc-registry-indexer.yml
tools/erc-repository-indexer/docs/registry_design.md
tools/erc-repository-indexer/erc-contract-indexer/README.md
tools/erc-repository-indexer/erc-contract-indexer/example.env
tools/erc-repository-indexer/erc-contract-indexer/src/runner.ts
tools/erc-repository-indexer/erc-contract-indexer/src/services/config.ts
tools/erc-repository-indexer/erc-contract-indexer/src/services/contractScanner.ts
tools/erc-repository-indexer/erc-contract-indexer/src/utils/helper.ts
tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/byteCodeAnalyzer.test.ts
tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/config.test.ts
tools/erc-repository-indexer/erc-contract-indexer/tests/unit/services/contractScanner.test.ts
tools/erc-repository-indexer/erc-contract-indexer/tests/unit/utils/helper.spec.ts

This PR introduces a new configuration parameter, `SCAN_CONTRACT_LIMIT`, to enhance the flexibility of the ERC Registry tool. Users can now dynamically configure the number of contracts scanned per operation, with a default value of 100 and a customizable range of 1 to 100.
Additionally, this setting overrides the `limit` parameter in the `next` link if one exists in storage or composed from `STARTING_POINT`. For example, if the `next` link is `/api/v1/contracts?limit=100&order=asc&contract.id=gt:0.0.5294198` and `SCAN_CONTRACT_LIMIT` is set to 30, the link will be updated to `/api/v1/contracts?limit=30&order=asc&contract.id=gt:0.0.5294198`.
Fixes #1131
**Checklist**

feat: added support for ERC Registry tool to dynamically configure the number of contracts to scan per operation

---

.github/workflows/erc-registry-indexer.yml

This PR updates the ERC Registry Indexer workflow to include ERC-1155, ensuring its support is reflected in newly created PRs.
Fixes #1172
**Checklist**

chore: added ERC-1155 to ERC Registry Indexer workflow

---

test/contract-admin-id/contractAdminId.js
test/system-contracts/hedera-token-service/utils.js

Added test for admin key and contract id validation (should be the same) after deploying a contract with hollow account.
Fixes #1007

test: validate contract and admin key in hollow account finalized as contract

---

lib/layer-zero/ExampleHTSConnector.sol
lib/layer-zero/ExampleHTSConnectorExistingToken.sol
lib/layer-zero/ExampleOApp.sol
lib/layer-zero/ExampleOFT.sol
lib/layer-zero/ExampleOFTAdapter.sol
lib/layer-zero/ExampleONFT.sol
lib/layer-zero/ExampleONFTAdapter.sol
lib/layer-zero/HTSConnector.sol
lib/layer-zero/HTSConnectorExistingToken.sol
lib/layer-zero/hts/HederaTokenService.sol
lib/layer-zero/hts/IHederaTokenService.sol
lib/layer-zero/hts/KeyHelper.sol

feat: migrate LZ contracts from the relay repo

---

test/openzeppelin/ERC-20/ERC20.js

- Made test dependencies explicit
- Fixed typo in function's signature
Fixes: #1209 
N/A
**Checklist**

fix: make tests dependency explicit

---

.github/workflows/manual-testing.yml
.github/workflows/tests.yml
test/system-contracts/hedera-token-service/hrc-904/AirdropContract.js
test/system-contracts/hedera-token-service/hrc-904/CancelAirdropContract.js
test/system-contracts/hedera-token-service/hrc-904/ClaimAirdropContract.js
test/system-contracts/hedera-token-service/hrc-904/IHRC904ProxyTests.js
test/system-contracts/hedera-token-service/hrc-904/TokenRejectContract.js

This PR splits HIP-904 tests into 3 batches in order to prevent flakiness (local node instance crashing due to high load) and reduce duration of job
Fixes #1309

feat: split up hip 904 tests into 3 batches

---

.github/workflows/erc-registry-indexer.yml

This PR updated ERC Registry workflow to reference the MNE repo under hiero-ledger organziation instead of hashgraph. 
Fixes #1312

fix: updated ERC Registry workflow to reference the MNE repo under hiero-ledger organziation

---

lib/layer-zero/HTSConnector.sol
lib/layer-zero/HTSConnectorExistingToken.sol

In the debit function, there is a call to the debitView function, which returns an `amountSentLD`, but in the transfer function, `_amountLD` is used.
Fixes #1478 
**Checklist**

feat: use `amountSentLD` in `.transferToken` on `_debit` function in LayerZero HTSConnector
